### ISSUE TITLE
Boost cpu not working even with root

### ISSUE THREAD

**Issue by GabiAle97** [ahmad1abbadi/darkos#14]
Tried "Boost cpu" option in safe mode, after rooting my phone and installing:

- pip (pkg install python-pip)
- psutil (pip install psutil)
- blessings (pip install blessings)

And got this Python Traceback error type:

```Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/cpu_boost.py", line 300, in <module>
    cpu_memory()
  File "/data/data/com.termux/files/usr/bin/cpu_boost.py", line 236, in cpu_memory
    cpu_info, cpu_freqs = cpu_info_future.result()
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/data/data/com.termux/files/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/bin/cpu_boost.py", line 23, in get_cpu_info
    "CPU Frequency": psutil.cpu_freq().current,
                     ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/__init__.py", line 1913, in cpu_freq
    ret = _psplatform.cpu_freq()
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_pslinux.py", line 786, in cpu_freq
    max_ = int(bcat(pjoin(path, "scaling_max_freq"))) / 1000
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 840, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 828, in cat
    with _open(fname) as f:
         ^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/psutil/_common.py", line 788, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/sys/devices/system/cpu/cpufreq/policy0/scaling_max_freq'```

**Comment by hisham2630** [comment]
disable selinux:
```
su -c setenforce 0
```
